### PR TITLE
Updated to format for current Splunk versions.

### PR DESCRIPTION
**Pull request by prof-ninjason**
Started with a clean Fork, and overwrote with my changes.

Must use the new Password Hashing arguments: `SPLUNK_PASSWORD: <changeme>`

`sudo` must be used to install software.

### CODE REVIEW

**Comment by prof-ninjason** [comment]
Updated sample data to the current year so that the mood_radiator app shows data on the dashboard.

**Comment by prof-ninjason** [comment]
Updated

**Comment by vincesesto** [comment]
Thanks for taking to time to make that change

**Comment by prof-ninjason** [comment]
Thank you for creating this great tool. I was using it yesterday and adjusted the dates in the CSV to 2021 so the data shown up in the query. 

Excellent work!

**Pull request merged**
